spring:
  redis:
    database: 2
    host: localhost
    port: 6379
    password:
    timeout: 3000
    pool:
      max-active: 50
      max-wait: 3000
      max-idle: 10
      min-idle: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: root@123
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      validation-query: SELECT 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
zk:
  url: zookeeper://localhost:2181
  servers: localhost:2181
  sessionTimeoutMs: 30000
  syncTimeMs: 5000
  connectionTimeoutMs: 5000
  root: /config_center/
#日志配置
logging:
  level:
    com.fittime.sport.dao: INFO
    org.springframework.hateoas: INFO
    org.springframework.data: INFO

