package com.zscat.pms.mapper;

import com.zscat.core.model.PmsMerchandise;
import com.zscat.core.model.PmsMerchandiseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
public interface PmsMerchandiseMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	int countByExample(PmsMerchandiseExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	int deleteByExample(PmsMerchandiseExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	int insert(PmsMerchandise record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	int insertSelective(PmsMerchandise record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	List<PmsMerchandise> selectByExample(PmsMerchandiseExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	PmsMerchandise selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	int updateByExampleSelective(@Param("record") PmsMerchandise record,
			@Param("example") PmsMerchandiseExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	int updateByExample(@Param("record") PmsMerchandise record, @Param("example") PmsMerchandiseExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	int updateByPrimaryKeySelective(PmsMerchandise record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	int updateByPrimaryKey(PmsMerchandise record);
	/***
     * 姓名：张古良
     * 修改时间:2019.7.14
     * @param name 菜品名字
     * @return 菜品列表
     */
    List<PmsMerchandise> queryPmsMerchandise(@Param("name") String name);
    /***
     * 姓名：张古良
     * 修改时间:2019.7.28
     * 根据菜品对象查询所有菜菜品
     * @param name 菜品对象
     * @return 菜品列表
     */
    List<PmsMerchandise> queryPmsMerchandiseList(PmsMerchandise pmsMerchandise);
    
}