package com.zscat.core.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PmsMerchandiseExample extends RuisModelObj{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	public PmsMerchandiseExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andProductIdIsNull() {
			addCriterion("product_id is null");
			return (Criteria) this;
		}

		public Criteria andProductIdIsNotNull() {
			addCriterion("product_id is not null");
			return (Criteria) this;
		}

		public Criteria andProductIdEqualTo(String value) {
			addCriterion("product_id =", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotEqualTo(String value) {
			addCriterion("product_id <>", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdGreaterThan(String value) {
			addCriterion("product_id >", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdGreaterThanOrEqualTo(String value) {
			addCriterion("product_id >=", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdLessThan(String value) {
			addCriterion("product_id <", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdLessThanOrEqualTo(String value) {
			addCriterion("product_id <=", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdLike(String value) {
			addCriterion("product_id like", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotLike(String value) {
			addCriterion("product_id not like", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdIn(List<String> values) {
			addCriterion("product_id in", values, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotIn(List<String> values) {
			addCriterion("product_id not in", values, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdBetween(String value1, String value2) {
			addCriterion("product_id between", value1, value2, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotBetween(String value1, String value2) {
			addCriterion("product_id not between", value1, value2, "productId");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andPictureIsNull() {
			addCriterion("picture is null");
			return (Criteria) this;
		}

		public Criteria andPictureIsNotNull() {
			addCriterion("picture is not null");
			return (Criteria) this;
		}

		public Criteria andPictureEqualTo(String value) {
			addCriterion("picture =", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureNotEqualTo(String value) {
			addCriterion("picture <>", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureGreaterThan(String value) {
			addCriterion("picture >", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureGreaterThanOrEqualTo(String value) {
			addCriterion("picture >=", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureLessThan(String value) {
			addCriterion("picture <", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureLessThanOrEqualTo(String value) {
			addCriterion("picture <=", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureLike(String value) {
			addCriterion("picture like", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureNotLike(String value) {
			addCriterion("picture not like", value, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureIn(List<String> values) {
			addCriterion("picture in", values, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureNotIn(List<String> values) {
			addCriterion("picture not in", values, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureBetween(String value1, String value2) {
			addCriterion("picture between", value1, value2, "picture");
			return (Criteria) this;
		}

		public Criteria andPictureNotBetween(String value1, String value2) {
			addCriterion("picture not between", value1, value2, "picture");
			return (Criteria) this;
		}

		public Criteria andUnitPriceIsNull() {
			addCriterion("unit_price is null");
			return (Criteria) this;
		}

		public Criteria andUnitPriceIsNotNull() {
			addCriterion("unit_price is not null");
			return (Criteria) this;
		}

		public Criteria andUnitPriceEqualTo(String value) {
			addCriterion("unit_price =", value, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceNotEqualTo(String value) {
			addCriterion("unit_price <>", value, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceGreaterThan(String value) {
			addCriterion("unit_price >", value, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceGreaterThanOrEqualTo(String value) {
			addCriterion("unit_price >=", value, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceLessThan(String value) {
			addCriterion("unit_price <", value, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceLessThanOrEqualTo(String value) {
			addCriterion("unit_price <=", value, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceLike(String value) {
			addCriterion("unit_price like", value, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceNotLike(String value) {
			addCriterion("unit_price not like", value, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceIn(List<String> values) {
			addCriterion("unit_price in", values, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceNotIn(List<String> values) {
			addCriterion("unit_price not in", values, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceBetween(String value1, String value2) {
			addCriterion("unit_price between", value1, value2, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceNotBetween(String value1, String value2) {
			addCriterion("unit_price not between", value1, value2, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andClassificationOfFoodIsNull() {
			addCriterion("classification_of_food is null");
			return (Criteria) this;
		}

		public Criteria andClassificationOfFoodIsNotNull() {
			addCriterion("classification_of_food is not null");
			return (Criteria) this;
		}

		public Criteria andClassificationOfFoodEqualTo(String value) {
			addCriterion("classification_of_food =", value, "classificationOfFood");
			return (Criteria) this;
		}

		public Criteria andClassificationOfFoodNotEqualTo(String value) {
			addCriterion("classification_of_food <>", value, "classificationOfFood");
			return (Criteria) this;
		}

		public Criteria andClassificationOfFoodGreaterThan(String value) {
			addCriterion("classification_of_food >", value, "classificationOfFood");
			return (Criteria) this;
		}

		public Criteria andClassificationOfFoodGreaterThanOrEqualTo(String value) {
			addCriterion("classification_of_food >=", value, "classificationOfFood");
			return (Criteria) this;
		}

		public Criteria andClassificationOfFoodLessThan(String value) {
			addCriterion("classification_of_food <", value, "classificationOfFood");
			return (Criteria) this;
		}

		public Criteria andClassificationOfFoodLessThanOrEqualTo(String value) {
			addCriterion("classification_of_food <=", value, "classificationOfFood");
			return (Criteria) this;
		}

		public Criteria andClassificationOfFoodLike(String value) {
			addCriterion("classification_of_food like", value, "classificationOfFood");
			return (Criteria) this;
		}

		public Criteria andClassificationOfFoodNotLike(String value) {
			addCriterion("classification_of_food not like", value, "classificationOfFood");
			return (Criteria) this;
		}

		public Criteria andClassificationOfFoodIn(List<String> values) {
			addCriterion("classification_of_food in", values, "classificationOfFood");
			return (Criteria) this;
		}

		public Criteria andClassificationOfFoodNotIn(List<String> values) {
			addCriterion("classification_of_food not in", values, "classificationOfFood");
			return (Criteria) this;
		}

		public Criteria andClassificationOfFoodBetween(String value1, String value2) {
			addCriterion("classification_of_food between", value1, value2, "classificationOfFood");
			return (Criteria) this;
		}

		public Criteria andClassificationOfFoodNotBetween(String value1, String value2) {
			addCriterion("classification_of_food not between", value1, value2, "classificationOfFood");
			return (Criteria) this;
		}

		public Criteria andStoreMerchandiseIdIsNull() {
			addCriterion("store_merchandise_id is null");
			return (Criteria) this;
		}

		public Criteria andStoreMerchandiseIdIsNotNull() {
			addCriterion("store_merchandise_id is not null");
			return (Criteria) this;
		}

		public Criteria andStoreMerchandiseIdEqualTo(Integer value) {
			addCriterion("store_merchandise_id =", value, "storeMerchandiseId");
			return (Criteria) this;
		}

		public Criteria andStoreMerchandiseIdNotEqualTo(Integer value) {
			addCriterion("store_merchandise_id <>", value, "storeMerchandiseId");
			return (Criteria) this;
		}

		public Criteria andStoreMerchandiseIdGreaterThan(Integer value) {
			addCriterion("store_merchandise_id >", value, "storeMerchandiseId");
			return (Criteria) this;
		}

		public Criteria andStoreMerchandiseIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("store_merchandise_id >=", value, "storeMerchandiseId");
			return (Criteria) this;
		}

		public Criteria andStoreMerchandiseIdLessThan(Integer value) {
			addCriterion("store_merchandise_id <", value, "storeMerchandiseId");
			return (Criteria) this;
		}

		public Criteria andStoreMerchandiseIdLessThanOrEqualTo(Integer value) {
			addCriterion("store_merchandise_id <=", value, "storeMerchandiseId");
			return (Criteria) this;
		}

		public Criteria andStoreMerchandiseIdIn(List<Integer> values) {
			addCriterion("store_merchandise_id in", values, "storeMerchandiseId");
			return (Criteria) this;
		}

		public Criteria andStoreMerchandiseIdNotIn(List<Integer> values) {
			addCriterion("store_merchandise_id not in", values, "storeMerchandiseId");
			return (Criteria) this;
		}

		public Criteria andStoreMerchandiseIdBetween(Integer value1, Integer value2) {
			addCriterion("store_merchandise_id between", value1, value2, "storeMerchandiseId");
			return (Criteria) this;
		}

		public Criteria andStoreMerchandiseIdNotBetween(Integer value1, Integer value2) {
			addCriterion("store_merchandise_id not between", value1, value2, "storeMerchandiseId");
			return (Criteria) this;
		}

		public Criteria andStateIsNull() {
			addCriterion("state is null");
			return (Criteria) this;
		}

		public Criteria andStateIsNotNull() {
			addCriterion("state is not null");
			return (Criteria) this;
		}

		public Criteria andStateEqualTo(Integer value) {
			addCriterion("state =", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotEqualTo(Integer value) {
			addCriterion("state <>", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThan(Integer value) {
			addCriterion("state >", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThanOrEqualTo(Integer value) {
			addCriterion("state >=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThan(Integer value) {
			addCriterion("state <", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThanOrEqualTo(Integer value) {
			addCriterion("state <=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateIn(List<Integer> values) {
			addCriterion("state in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotIn(List<Integer> values) {
			addCriterion("state not in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateBetween(Integer value1, Integer value2) {
			addCriterion("state between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotBetween(Integer value1, Integer value2) {
			addCriterion("state not between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andOrderStateIsNull() {
			addCriterion("order_state is null");
			return (Criteria) this;
		}

		public Criteria andOrderStateIsNotNull() {
			addCriterion("order_state is not null");
			return (Criteria) this;
		}

		public Criteria andOrderStateEqualTo(Integer value) {
			addCriterion("order_state =", value, "orderState");
			return (Criteria) this;
		}

		public Criteria andOrderStateNotEqualTo(Integer value) {
			addCriterion("order_state <>", value, "orderState");
			return (Criteria) this;
		}

		public Criteria andOrderStateGreaterThan(Integer value) {
			addCriterion("order_state >", value, "orderState");
			return (Criteria) this;
		}

		public Criteria andOrderStateGreaterThanOrEqualTo(Integer value) {
			addCriterion("order_state >=", value, "orderState");
			return (Criteria) this;
		}

		public Criteria andOrderStateLessThan(Integer value) {
			addCriterion("order_state <", value, "orderState");
			return (Criteria) this;
		}

		public Criteria andOrderStateLessThanOrEqualTo(Integer value) {
			addCriterion("order_state <=", value, "orderState");
			return (Criteria) this;
		}

		public Criteria andOrderStateIn(List<Integer> values) {
			addCriterion("order_state in", values, "orderState");
			return (Criteria) this;
		}

		public Criteria andOrderStateNotIn(List<Integer> values) {
			addCriterion("order_state not in", values, "orderState");
			return (Criteria) this;
		}

		public Criteria andOrderStateBetween(Integer value1, Integer value2) {
			addCriterion("order_state between", value1, value2, "orderState");
			return (Criteria) this;
		}

		public Criteria andOrderStateNotBetween(Integer value1, Integer value2) {
			addCriterion("order_state not between", value1, value2, "orderState");
			return (Criteria) this;
		}

		public Criteria andEvaluateStateIsNull() {
			addCriterion("evaluate_state is null");
			return (Criteria) this;
		}

		public Criteria andEvaluateStateIsNotNull() {
			addCriterion("evaluate_state is not null");
			return (Criteria) this;
		}

		public Criteria andEvaluateStateEqualTo(Integer value) {
			addCriterion("evaluate_state =", value, "evaluateState");
			return (Criteria) this;
		}

		public Criteria andEvaluateStateNotEqualTo(Integer value) {
			addCriterion("evaluate_state <>", value, "evaluateState");
			return (Criteria) this;
		}

		public Criteria andEvaluateStateGreaterThan(Integer value) {
			addCriterion("evaluate_state >", value, "evaluateState");
			return (Criteria) this;
		}

		public Criteria andEvaluateStateGreaterThanOrEqualTo(Integer value) {
			addCriterion("evaluate_state >=", value, "evaluateState");
			return (Criteria) this;
		}

		public Criteria andEvaluateStateLessThan(Integer value) {
			addCriterion("evaluate_state <", value, "evaluateState");
			return (Criteria) this;
		}

		public Criteria andEvaluateStateLessThanOrEqualTo(Integer value) {
			addCriterion("evaluate_state <=", value, "evaluateState");
			return (Criteria) this;
		}

		public Criteria andEvaluateStateIn(List<Integer> values) {
			addCriterion("evaluate_state in", values, "evaluateState");
			return (Criteria) this;
		}

		public Criteria andEvaluateStateNotIn(List<Integer> values) {
			addCriterion("evaluate_state not in", values, "evaluateState");
			return (Criteria) this;
		}

		public Criteria andEvaluateStateBetween(Integer value1, Integer value2) {
			addCriterion("evaluate_state between", value1, value2, "evaluateState");
			return (Criteria) this;
		}

		public Criteria andEvaluateStateNotBetween(Integer value1, Integer value2) {
			addCriterion("evaluate_state not between", value1, value2, "evaluateState");
			return (Criteria) this;
		}

		public Criteria andCreateByIsNull() {
			addCriterion("create_by is null");
			return (Criteria) this;
		}

		public Criteria andCreateByIsNotNull() {
			addCriterion("create_by is not null");
			return (Criteria) this;
		}

		public Criteria andCreateByEqualTo(Integer value) {
			addCriterion("create_by =", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotEqualTo(Integer value) {
			addCriterion("create_by <>", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByGreaterThan(Integer value) {
			addCriterion("create_by >", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByGreaterThanOrEqualTo(Integer value) {
			addCriterion("create_by >=", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByLessThan(Integer value) {
			addCriterion("create_by <", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByLessThanOrEqualTo(Integer value) {
			addCriterion("create_by <=", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByIn(List<Integer> values) {
			addCriterion("create_by in", values, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotIn(List<Integer> values) {
			addCriterion("create_by not in", values, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByBetween(Integer value1, Integer value2) {
			addCriterion("create_by between", value1, value2, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotBetween(Integer value1, Integer value2) {
			addCriterion("create_by not between", value1, value2, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("create_date =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("create_date <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("create_date >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("create_date >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("create_date <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("create_date <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("create_date in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("create_date not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("create_date between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("create_date not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andUpdateByIsNull() {
			addCriterion("update_by is null");
			return (Criteria) this;
		}

		public Criteria andUpdateByIsNotNull() {
			addCriterion("update_by is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateByEqualTo(Integer value) {
			addCriterion("update_by =", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByNotEqualTo(Integer value) {
			addCriterion("update_by <>", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByGreaterThan(Integer value) {
			addCriterion("update_by >", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByGreaterThanOrEqualTo(Integer value) {
			addCriterion("update_by >=", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByLessThan(Integer value) {
			addCriterion("update_by <", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByLessThanOrEqualTo(Integer value) {
			addCriterion("update_by <=", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByIn(List<Integer> values) {
			addCriterion("update_by in", values, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByNotIn(List<Integer> values) {
			addCriterion("update_by not in", values, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByBetween(Integer value1, Integer value2) {
			addCriterion("update_by between", value1, value2, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByNotBetween(Integer value1, Integer value2) {
			addCriterion("update_by not between", value1, value2, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("update_date is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("update_date is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateEqualTo(Date value) {
			addCriterion("update_date =", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotEqualTo(Date value) {
			addCriterion("update_date <>", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThan(Date value) {
			addCriterion("update_date >", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("update_date >=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThan(Date value) {
			addCriterion("update_date <", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("update_date <=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIn(List<Date> values) {
			addCriterion("update_date in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotIn(List<Date> values) {
			addCriterion("update_date not in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateBetween(Date value1, Date value2) {
			addCriterion("update_date between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("update_date not between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andRemarksIsNull() {
			addCriterion("remarks is null");
			return (Criteria) this;
		}

		public Criteria andRemarksIsNotNull() {
			addCriterion("remarks is not null");
			return (Criteria) this;
		}

		public Criteria andRemarksEqualTo(Integer value) {
			addCriterion("remarks =", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotEqualTo(Integer value) {
			addCriterion("remarks <>", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksGreaterThan(Integer value) {
			addCriterion("remarks >", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksGreaterThanOrEqualTo(Integer value) {
			addCriterion("remarks >=", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksLessThan(Integer value) {
			addCriterion("remarks <", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksLessThanOrEqualTo(Integer value) {
			addCriterion("remarks <=", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksIn(List<Integer> values) {
			addCriterion("remarks in", values, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotIn(List<Integer> values) {
			addCriterion("remarks not in", values, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksBetween(Integer value1, Integer value2) {
			addCriterion("remarks between", value1, value2, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotBetween(Integer value1, Integer value2) {
			addCriterion("remarks not between", value1, value2, "remarks");
			return (Criteria) this;
		}

		public Criteria andEnableIsNull() {
			addCriterion("enable is null");
			return (Criteria) this;
		}

		public Criteria andEnableIsNotNull() {
			addCriterion("enable is not null");
			return (Criteria) this;
		}

		public Criteria andEnableEqualTo(Integer value) {
			addCriterion("enable =", value, "enable");
			return (Criteria) this;
		}

		public Criteria andEnableNotEqualTo(Integer value) {
			addCriterion("enable <>", value, "enable");
			return (Criteria) this;
		}

		public Criteria andEnableGreaterThan(Integer value) {
			addCriterion("enable >", value, "enable");
			return (Criteria) this;
		}

		public Criteria andEnableGreaterThanOrEqualTo(Integer value) {
			addCriterion("enable >=", value, "enable");
			return (Criteria) this;
		}

		public Criteria andEnableLessThan(Integer value) {
			addCriterion("enable <", value, "enable");
			return (Criteria) this;
		}

		public Criteria andEnableLessThanOrEqualTo(Integer value) {
			addCriterion("enable <=", value, "enable");
			return (Criteria) this;
		}

		public Criteria andEnableIn(List<Integer> values) {
			addCriterion("enable in", values, "enable");
			return (Criteria) this;
		}

		public Criteria andEnableNotIn(List<Integer> values) {
			addCriterion("enable not in", values, "enable");
			return (Criteria) this;
		}

		public Criteria andEnableBetween(Integer value1, Integer value2) {
			addCriterion("enable between", value1, value2, "enable");
			return (Criteria) this;
		}

		public Criteria andEnableNotBetween(Integer value1, Integer value2) {
			addCriterion("enable not between", value1, value2, "enable");
			return (Criteria) this;
		}

		public Criteria andNumberIsNull() {
			addCriterion("number is null");
			return (Criteria) this;
		}

		public Criteria andNumberIsNotNull() {
			addCriterion("number is not null");
			return (Criteria) this;
		}

		public Criteria andNumberEqualTo(Integer value) {
			addCriterion("number =", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberNotEqualTo(Integer value) {
			addCriterion("number <>", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberGreaterThan(Integer value) {
			addCriterion("number >", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("number >=", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberLessThan(Integer value) {
			addCriterion("number <", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberLessThanOrEqualTo(Integer value) {
			addCriterion("number <=", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberIn(List<Integer> values) {
			addCriterion("number in", values, "number");
			return (Criteria) this;
		}

		public Criteria andNumberNotIn(List<Integer> values) {
			addCriterion("number not in", values, "number");
			return (Criteria) this;
		}

		public Criteria andNumberBetween(Integer value1, Integer value2) {
			addCriterion("number between", value1, value2, "number");
			return (Criteria) this;
		}

		public Criteria andNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("number not between", value1, value2, "number");
			return (Criteria) this;
		}

		public Criteria andCountIsNull() {
			addCriterion("count is null");
			return (Criteria) this;
		}

		public Criteria andCountIsNotNull() {
			addCriterion("count is not null");
			return (Criteria) this;
		}

		public Criteria andCountEqualTo(Integer value) {
			addCriterion("count =", value, "count");
			return (Criteria) this;
		}

		public Criteria andCountNotEqualTo(Integer value) {
			addCriterion("count <>", value, "count");
			return (Criteria) this;
		}

		public Criteria andCountGreaterThan(Integer value) {
			addCriterion("count >", value, "count");
			return (Criteria) this;
		}

		public Criteria andCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("count >=", value, "count");
			return (Criteria) this;
		}

		public Criteria andCountLessThan(Integer value) {
			addCriterion("count <", value, "count");
			return (Criteria) this;
		}

		public Criteria andCountLessThanOrEqualTo(Integer value) {
			addCriterion("count <=", value, "count");
			return (Criteria) this;
		}

		public Criteria andCountIn(List<Integer> values) {
			addCriterion("count in", values, "count");
			return (Criteria) this;
		}

		public Criteria andCountNotIn(List<Integer> values) {
			addCriterion("count not in", values, "count");
			return (Criteria) this;
		}

		public Criteria andCountBetween(Integer value1, Integer value2) {
			addCriterion("count between", value1, value2, "count");
			return (Criteria) this;
		}

		public Criteria andCountNotBetween(Integer value1, Integer value2) {
			addCriterion("count not between", value1, value2, "count");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pms_merchandise
	 * @mbg.generated  Tue Jul 30 11:33:07 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pms_merchandise
     *
     * @mbg.generated do_not_delete_during_merge Tue Jul 30 11:25:21 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}