server:
  port: 8803

spring:
  application:
    name: ums-service 
  profiles:
    active: dev 
  redis:
    database: 1
    host: localhost
    port: 6379
    password:
    timeout: 3000
    pool:
      max-active: 50
      max-wait: 3000
      max-idle: 10
      min-idle: 1 

mybatis:
  mapper-locations: classpath*:com/**/mapper/*.xml

zk:
  dubbo-port: 20881
  url: zookeeper://localhost:2181
  servers: localhost:2181
  sessionTimeoutMs: 30000
  syncTimeMs: 5000
  connectionTimeoutMs: 5000
  root: /config_center/

#===OSS start===
aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: test
    accessKeySecret: test
    bucketName: macro-oss
    maxSize: 10
    callback: http://localhost:8080/aliyun/oss/callback
    policy:
      expire: 300
    dir:
      prefix: mall/images/
#===OSS end===

#日志配置
logging:
  level:
    com.fittime.sport.dao: INFO
    org.springframework.hateoas: INFO
    org.springframework.data: INFO

